services:
  - type: web
    name: medalze-backend
    runtime: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn -w 1 app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: MODEL_PATH
        value: model/chexnet.pth
      - key: GEMINI_API_KEY
        sync: false
